a=int(input("Enter 1st Number:"));
b=int(input("Enter 2nd Number:"));
add=a+b;
sub=a-b;
mul=a*b;
div=a/b;
print("Addition:",add);
print("subtraction:",sub);
print("multiplication:",mul);
print("Division:",add);
